[system]

[log]
director = "log" 
encode-level = "LowercaseColorLevelEncoder" #LowercaseLevelEncoder,LowercaseColorLevelEncoder,CapitalLevelEncoder,CapitalColorLevelEncoder
format = "text" # text,json
level = "debug" # debug,info,warn,error,dpanic,panic,fatal
# link-name = "lastest_log" 
log-console = true 
prefix = "[OrderService]" 
show-line = true 
stacktrace-key = "" #key for stacktrace, space for no stacktrace

[jianjiao]
app-code = "DEBC861AAC935A8C168F53CF0990067F"
app-key = "AKID445463d641137eda25e06611b1143a77"
app-secret = "e7001862c9b359ca9d3a9ec7cbb8d66c"
