[system]

[log]
director = "log" 
encode-level = "LowercaseColorLevelEncoder" #LowercaseLevelEncoder,LowercaseColorLevelEncoder,CapitalLevelEncoder,CapitalColorLevelEncoder
format = "text" # text,json
level = "debug" # debug,info,warn,error,dpanic,panic,fatal
link-name = "lastest_log" 
log-console = true 
prefix = "[OrderService]" 
show-line = true 
stacktrace-key = "" #key for stacktrace, space for no stacktrace
